export const HEBREW = {
  websiteTitle: "אתר לדוגמא",
  register: "הרשמה",
  login: "כניסה",
  username: "שם משתמש",
  password: "סיסמא",
  confirmPassword: "אישור סיסמא",
  isAdmin: "מנהל מערכת",
  requiredField: "שדה חובה",
  passwordsShouldMatch: "הסיסמאות צריכות להתאים",
  alreadyRegistered: "כבר רשומים?",
  notRegistered: "לא רשומים?",
  loginHere: "היכנסו כאן",
  signUpHere: "הירשמו כאן",
  loginError: "שגיאה בהתחברות",
  logout: "יציאה",
  addDepartment: "הוספת מחלקה",
  departmentName: "שם המחלקה",
  departmentCode: "קוד המחלקה",
  rooms: "חדרים",
  roomName: "שם החדר",
  roomCode: "קוד החדר",
  addRoom: "הוסף חדר",
  save: "שמירה",
};
