name: CI

on:
  push:
    branches:
      - "development"
  pull_request:
    types:
      - "opened"
      - "synchronize"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  up_to_date:
    name: "Up to Date"
    runs-on: "self-hosted"
    outputs:
      updated: ${{ steps.check.outputs.updated }}
    steps:
      - name: Check if Up to Date
        id: check
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          PR_SHA="${{ github.event.pull_request.head.sha }}"

          BASE_SHA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${BASE_BRANCH}" | jq -r '.sha')

          if [ "$BASE_SHA" == "$PR_SHA" ]; then
            echo "updated=1" >> $GITHUB_OUTPUT
          else
            echo "updated=0" >> $GITHUB_OUTPUT
          fi

  ci:
    name: "Continuous Integration"
    runs-on: "self-hosted"
    needs: "up_to_date"
    if: ${{needs.up_to_date.outputs.updated}}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Turbo Cache"
        uses: "actions/cache@v4"
        with:
          path: ".turbo"
          key: "${{ runner.os }}-turbo-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-turbo-"

      - name: "Setup NodeJS"
        uses: "actions/setup-node@v4"
        with:
          node-version-file: ".nvmrc"

      - name: "Setup PNPM"
        uses: "pnpm/action-setup@v3"
        with:
          run_install: true
          dest: "${{ runner.temp }}/.pnpm"

      - name: "Validate Commit (Push)"
        if: github.event_name == 'push'
        run: "pnpm exec commitlint --last --verbose"

      - name: "Validate Commits (PR)"
        if: github.event_name == 'pull_request'
        run: |
          pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: "Turbo Pipeline"
        run: "pnpm run pipeline --cache-dir=.turbo"

      # - name: "Unit Tests"
      #   run: "pnpm exec turbo test"

      # - name: "End-to-End Tests"
      #   uses: "cypress-io/github-action@v6"
      #   with:
      #     install: false
      #     wait-on: "http://127.0.0.1:8080/api/health"
      #     wait-on-timeout: 120
      #     start: |
      #       pnpm --dir clients/app e2e
      #       pnpm --dir server e2e
